Added operator tests to CI

diff --git a/tests/resources/utils/send_data_batch b/tests/resources/utils/send_data_batch
--- a/tests/resources/utils/send_data_batch
+++ b/tests/resources/utils/send_data_batch
@@ -22,13 +22,18 @@ oc project $ODHPROJECT 2>&1 1>/dev/null
 
 check_for_reception () {
   while true
+  CHECKS=1
   do
-    THRESH=$(( $1 * 505 / 1000 ))
+    THRESH=$(( $1 * 250 / 1000 ))
     N_OBS=$(oc exec $TRUSTY_POD  -c trustyai-service -- bash -c "cat /inputs/$2-metadata.json"  | jq .observations)
     echo -ne "\rMaking sure TrustyAI $2 dataset contains at least $THRESH points, has $N_OBS";
     if (( $N_OBS > $THRESH )); then
       break
+    elif (( CHECKS > 10)); then
+      echo "ERROR: Message reception timeout";
+      exit 1
     else
+      CHECKS=$((CHECKS+1))
       sleep 1
     fi
   done
